DROP DATABASE IF EXISTS topics;
CREATE DATABASE topics;
USE topics;
CREATE TABLE topic (topic_id int NOT NULL AUTO_INCREMENT, topic_name varchar(255) NOT NULL, topic_description varchar(255) NOT NULL, PRIMARY KEY (topic_id) );
INSERT INTO topic VALUES (NULL,  'Administration', 'Management, maintenance, updates and control of servers, routers, clients and other network components.');
INSERT INTO topic VALUES (NULL, 'Apache', 'Apache is the most popular Web server software. It enables a computer to host one or more websites that can be accessed over the Internet using a Web browser.');
INSERT INTO topic VALUES (NULL, 'Audio / Video', 'Music and Film Production using Logic Pro and Final Cut Pro.');
INSERT INTO topic VALUES (NULL, 'Automation', 'Agentless management of installs, deployments and many other tasks that can be automated.');
INSERT INTO topic VALUES (NULL, 'Bash', 'A command language interpreter that executes commands entered at a command prompt and process text file input.');
INSERT INTO topic VALUES (NULL, 'Blender', 'Open source 3D creation suite. It supports modeling, rigging, animation, simulation, rendering, compositing and motion tracking, video editing and a 2D animation pipeline.');
INSERT INTO topic VALUES (NULL, 'Cryptocurrency', 'A digital record with each transaction linked together in single list called a chain.  Used by cryptocurrencies such as Bitcoin, and many other applications.');
INSERT INTO topic VALUES (NULL, 'Bootstrap', 'A CSS framework directed at responsive, mobile-first front-end web development.');
INSERT INTO topic VALUES (NULL, 'C/C++/Obj-C', 'A family of programming languages that derive syntax from the original.  C++ and Objective C are supersets of C.');
INSERT INTO topic VALUES (NULL, 'Codeigniter', 'An open-source software rapid development web framework, mostly used for building dynamic web sites with PHP.');
INSERT INTO topic VALUES (NULL, 'Command Line', 'A command-line interface (CLI) processes commands in the form of lines of text.');
INSERT INTO topic VALUES (NULL, 'C Preprocessor', 'Macro preprocessor for the C, Objective-C and C++ computer programming languages, allowing header files, macro expansions, conditional compilation, and line control.');
INSERT INTO topic VALUES (NULL, 'CSS', 'Cascading Style Sheets (CSS) is a style sheet language used for describing the presentation of a document written in a markup language such as HTML.');
INSERT INTO topic VALUES (NULL, 'Cyber Tools', 'Tools for defensive and offensive cybersecurity, networking, systems, web technologies, and databases.');
INSERT INTO topic VALUES (NULL, 'Dev Tools', 'Development tools such as linkers, compilers, code editors, GUI designers, IDEs , assemblers, debuggers, and other tools.');
INSERT INTO topic VALUES (NULL, 'Django', 'Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.');
INSERT INTO topic VALUES (NULL, 'Editors', 'Visual Studio Code, BBEdit, vim, emacs and other source code others.');
INSERT INTO topic VALUES (NULL, 'HTML', 'HTML5 is the newest markup language used for structuring and presenting content on the World Wide Web.');
INSERT INTO topic VALUES (NULL, 'ImageMagick', 'Cross-platform software suite for displaying, creating, converting, modifying, and editing raster images.');
INSERT INTO topic VALUES (NULL, 'iOS', 'iOS (formerly iPhone OS) is a mobile operating system created and developed by Apple Inc.exclusively for its hardware.');
INSERT INTO topic VALUES (NULL, 'Java', 'Java is a class-based, object-oriented programming language intending to let application developers write once, run anywhere (WORA).');
INSERT INTO topic VALUES (NULL, 'Javascript', 'Javascript is high-level, just-in-time compiled, and multi-paradigm language, with curly-bracket syntax, dynamic typing, object-orientation, and first-class functions.');
INSERT INTO topic VALUES (NULL, 'jQuery', 'A Javascript library designed to simplify HTML DOM tree traversal and manipulation, as well as event handling, CSS animation, and Ajax.');
INSERT INTO topic VALUES (NULL, 'Linux', 'A family of open-source Unix-like operating systems based on the Linux kernel, typically packaged in a Linux distribution.');
INSERT INTO topic VALUES (NULL, 'MySQL', ' An open-source relational database management system that is typically used with other programs to implement applications that need relational database capability.');
INSERT INTO topic VALUES (NULL, 'Perl', 'Perl refers to Perl 5, but from 2000 to 2019 it also referred to its redesigned sister language, Perl 6, before the latter''s name was officially changed to Raku in October 2019.');
INSERT INTO topic VALUES (NULL, 'Photoshop', 'Adobe Photoshop is a raster graphics editor developed and published by Adobe Inc. for Windows and macOS.');
INSERT INTO topic VALUES (NULL, 'PHP', 'PHP is a general-purpose scripting language especially suited to web development.');
INSERT INTO topic VALUES (NULL, 'Python', 'Python is an interpreted high-level general-purpose programming language. Python''s design philosophy emphasizes code readability with its notable use of significant indentation.');
INSERT INTO topic VALUES (NULL, 'Raspberry', 'Raspberry Pi is a series of small single-board computers developed in the United Kingdom by the Raspberry Pi Foundation in association with Broadcom.');
INSERT INTO topic VALUES (NULL, 'Ruby', 'Ruby is an interpreted, high-level, general-purpose programming language. It was designed and developed in the mid-1990s by Yukihiro Matz Matsumoto in Japan.');
INSERT INTO topic VALUES (NULL, 'Security', 'Cybersecurity refers to the security of devices such as computers and smartphones, as well as private and public networks, and the Internet.');
INSERT INTO topic VALUES (NULL, 'Shortcuts', 'Keyboard shortcuts are a means for invoking one or more commands using the keyboard rather than a menu, a pointing device,  a user interface, or via a command-line interface.');
INSERT INTO topic VALUES (NULL, 'SQL', 'Structured Query Language)] is a domain-specific language used in programming and designed for managing data held in a relational database management system (RDBMS).');
INSERT INTO topic VALUES (NULL, 'SSL', 'Transport Layer Security (TLS), and its now-deprecated predecessor, Secure Sockets Layer (SSL), are cryptographic protocols designed to provide communications security over a computer network.');
INSERT INTO topic VALUES (NULL, 'Swift', 'Swift is a general-purpose, multi-paradigm, compiled programming language developed by Apple Inc. and the open-source community, first released in 2014.');
INSERT INTO topic VALUES (NULL, 'SwiftUI', 'SwiftUI is an innovative, simple way to build user interfaces across all Apple platforms with the power of Swift.');
INSERT INTO topic VALUES (NULL, 'Unreal', 'Unreal Engine is a state-of-the-art real-time editor that features photorealistic rendering, dynamic physics and effects, lifelike animation, robust data translation, and much more.');
INSERT INTO topic VALUES (NULL, 'Windows', 'a group of several proprietary graphical operating system families, all of which are developed and marketed by Microsoft.');
INSERT INTO topic VALUES (NULL, 'Xcode', ' Apple''s integrated development environment (IDE) for macOS, used to develop software for macOS, iOS, iPadOS, watchOS, and tvOS.');
